dataset:
  concat_history: true
  image_features_test_h5: data/features_faster_rcnn_x101_test.h5
  image_features_train_h5: data/features_faster_rcnn_x101_train.h5
  image_features_val_h5: data/features_faster_rcnn_x101_val.h5
  img_norm: 1
  max_sequence_length: 20
  vocab_min_count: 5
  word_counts_json: data/visdial_1.0_word_counts_train.json
model:
  decoder: disc
  dropout: 0.5
  encoder: lf
  img_feature_size: 2048
  lstm_hidden_size: 512
  lstm_num_layers: 2
  word_embedding_size: 300
solver:
  batch_size: 128
  initial_lr: 0.01
  lr_gamma: 0.1
  lr_milestones:
  - 4
  - 7
  - 10
  num_epochs: 20
  training_splits: train
  warmup_epochs: 1
  warmup_factor: 0.2
